import Image from 'next/image';
import { ArrowRightIcon, CheckIcon } from '@heroicons/react/24/outline';
import SiteHeader from '@/components/SiteHeader';
import SiteFooter from '@/components/SiteFooter';
import data from '@/data/site.en.json';

export const metadata={title:'Festival Prefabrik | Modern Prefabricated Houses',description:'Modern prefabricated and steel house solutions, manufactured in Türkiye and delivered nationwide.'};
export default function EnglishHome(){return <main><SiteHeader locale="en"/>
 <section className="hero"><video className="hero-video" autoPlay muted loop playsInline preload="metadata" poster="https://www.festivalprefabrik.com/resimbas.asp?rsm=20170109_130200-15.jpg&nrs=slider&w=1920&h=800&s=1" aria-label="Festival Prefabrik projects"><source src="/media/slider-festival.mp4" type="video/mp4"/></video><div className="hero-shade"/><div className="hero-grid"/><div className="hero-copy wrap"><div className="eyebrow"><span/> Built with confidence in Türkiye</div><h1>A new life is<br/><em>closer than</em><br/>you think.</h1><p>We create modern prefabricated and steel buildings that are fast, safe and designed around your needs.</p><div className="hero-actions"><a className="primary" href="/en/models">Explore models <ArrowRightIcon/></a><a className="play" href="#process"><span>▶</span> How we build</a></div></div></section>
 <section className="stats wrap">{[['20+','Years of experience'],['500+','Completed buildings'],['81','Cities delivered'],['10 years','Structural warranty']].map(([v,l],i)=><div key={l}><b>{v}</b><span>{l}</span>{i<3&&<i/>}</div>)}</section>
 <section className="intro wrap" id="projects"><div><span className="section-kicker">Featured models</span><h2>Find the home<br/><em>closest to your dream.</em></h2></div><p>Discover durable and energy-efficient prefabricated homes planned for different needs, lifestyles and budgets.</p></section>
 <section className="project-grid wrap en-projects">{data.projects.map(p=><article key={p.slug}><a href={`/en/models/${p.slug}`}><div className="project-img"><Image src={p.image} fill alt={p.title} sizes="25vw"/><span>View details <ArrowRightIcon/></span></div><div className="project-info"><h3>{p.title}</h3><p>{p.area} <i/> {p.rooms}</p></div></a></article>)}</section>
 <section className="why" id="why"><div className="why-image"><Image src="https://www.festivalprefabrik.com/resim.asp?urun=222&w=1100&h=900&nrs=urun" fill alt="Steel house" sizes="50vw"/></div><div className="why-copy"><span className="section-kicker light">Why Festival Prefabrik?</span><h2>Living spaces<br/>built on trust.</h2><p>We manufacture your building for generations of safe and comfortable use.</p><div className="benefits">{[['Earthquake resistant','Engineered structural systems compliant with standards.'],['Fast production','Manufacturing and assembly completed in weeks.'],['Thermal insulation','Comfortable and energy-efficient in every season.'],['Transparent process','Clear communication from planning to delivery.']].map(([a,b])=><div key={a}><span><CheckIcon/></span><section><b>{a}</b><small>{b}</small></section></div>)}</div></div></section>
 <section className="process" id="process"><div className="wrap"><span className="section-kicker">Your home in four steps</span><h2>From concept to turnkey.</h2><div className="steps">{[['01','Discovery'],['02','Design'],['03','Production'],['04','Assembly & delivery']].map(([n,t],i)=><div key={n}><b>{n}</b><span>{t}</span>{i<3&&<ArrowRightIcon/>}</div>)}</div></div></section>
 <section className="cta" id="contact"><div className="wrap cta-inner"><div><span className="section-kicker light">Let’s discuss your project</span><h2>Let’s bring your dream<br/>building to life.</h2><p>Our team will listen to your needs and prepare a free preliminary proposal.</p></div><div className="contact-box"><span>Call us now</span><a href={`tel:${data.mobile.replaceAll(' ','')}`}>{data.mobile}</a><small>Weekdays 08:30 — 18:00</small><a className="white-btn" href="/en/quote">Request a quote <ArrowRightIcon/></a></div></div></section><SiteFooter locale="en"/></main>}
